import { typography } from '../../tokens/typography';

export const textStyles = {
  xs: {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xs,
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading4,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xs,
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading4,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xs,
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading4,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xs,
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading4,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xs,
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading4,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xs,
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading4,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xs,
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading4,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },
  
  sm: {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.sm,
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading5,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.sm,
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading5,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.sm,
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading5,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.sm,
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading5,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.sm,
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading5,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.sm,
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading5,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.sm,
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading5,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  md: {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.md,
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading6,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.md,
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading6,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.md,
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading6,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.md,
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading6,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.md,
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading6,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.md,
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading6,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.md,
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading6,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  lg: {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.lg,
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading7,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.lg,
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading7,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.lg,
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading7,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.lg,
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading7,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.lg,
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading7,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.lg,
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading7,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.lg,
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading7,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  xl: {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xl,
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading8,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xl,
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading8,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xl,
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading8,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xl,
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading8,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xl,
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading8,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xl,
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading8,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size.xl,
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading8,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  '2xl': {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['2xl'],
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading9,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['2xl'],
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading9,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['2xl'],
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading9,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['2xl'],
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading9,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['2xl'],
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading9,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['2xl'],
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading9,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['2xl'],
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading9,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  '3xl': {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['3xl'],
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading10,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['3xl'],
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading10,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['3xl'],
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading10,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['3xl'],
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading10,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['3xl'],
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading10,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['3xl'],
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading10,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['3xl'],
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading10,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  '4xl': {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['4xl'],
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading11,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['4xl'],
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading11,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['4xl'],
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading11,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['4xl'],
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading11,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['4xl'],
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading11,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['4xl'],
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading11,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['4xl'],
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading11,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  '5xl': {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['5xl'],
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading12,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['5xl'],
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading12,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['5xl'],
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading12,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['5xl'],
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading12,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['5xl'],
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading12,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['5xl'],
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading12,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['5xl'],
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading12,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  '6xl': {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['6xl'],
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading13,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['6xl'],
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading13,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['6xl'],
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading13,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['6xl'],
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading13,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['6xl'],
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading13,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['6xl'],
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading13,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['6xl'],
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading13,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  '7xl': {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['7xl'],
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading14,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['7xl'],
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading14,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['7xl'],
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading14,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['7xl'],
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading14,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['7xl'],
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading14,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['7xl'],
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading14,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['7xl'],
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading14,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  '8xl': {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['8xl'],
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['8xl'],
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['8xl'],
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['8xl'],
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['8xl'],
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['8xl'],
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['8xl'],
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  '9xl': {
    light: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['9xl'],
      fontWeight: typography.desktop.weight.light,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    normal: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['9xl'],
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['9xl'],
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['9xl'],
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    bold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['9xl'],
      fontWeight: typography.desktop.weight.bold,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    extrabold: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['9xl'],
      fontWeight: typography.desktop.weight.extrabold,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    black: {
      fontFamily: typography.fontFamily.body,
      fontSize: typography.desktop.size['9xl'],
      fontWeight: typography.desktop.weight.black,
      lineHeight: typography.desktop.lineHeight.leading15,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  // Special styles
  quote: {
    normal: {
      fontFamily: typography.fontFamily.quote,
      fontSize: typography.desktop.size.xl,
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading8,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.quote,
      fontSize: typography.desktop.size.xl,
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading8,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    semibold: {
      fontFamily: typography.fontFamily.quote,
      fontSize: typography.desktop.size.xl,
      fontWeight: typography.desktop.weight.semibold,
      lineHeight: typography.desktop.lineHeight.leading8,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },

  code: {
    normal: {
      fontFamily: typography.fontFamily.code,
      fontSize: typography.desktop.size.sm,
      fontWeight: typography.desktop.weight.normal,
      lineHeight: typography.desktop.lineHeight.leading5,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
    medium: {
      fontFamily: typography.fontFamily.code,
      fontSize: typography.desktop.size.sm,
      fontWeight: typography.desktop.weight.medium,
      lineHeight: typography.desktop.lineHeight.leading5,
      letterSpacing: typography.desktop.letterSpacing.normal,
    },
  },
};

export default textStyles;
